# Generated by Django 3.2.3 on 2021-05-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pensionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad_actual', models.IntegerField(default=0)),
                ('edad_retiro', models.IntegerField(default=0)),
                ('saldo_acumulado', models.FloatField(default=0.0)),
                ('ahorro_mensual', models.FloatField(default=0.0)),
                ('genero', models.BooleanField(default=True)),
            ],
        ),
    ]
